language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - secure: PUH13S6WprYWdPASedvP7CwSJv/bYU6+O3QVPGeNazMiaToeRkYl7oOrAB2xeWwsMK0w/rubqDAgetijiPdrsn5lGqQNPZEoU8xrdnc5AmqTSS+qJOmQBWvZOeB7qO7RhXhPliQOC/vbQ7CnM7YIHGzFcnw4mE08jXd8YmTOwxU=
  - secure: J8FCPHtFHk6pL/nJcVSFECxxx4ldmJj3Xe7k+h/IWAQ4l0YFzlAeM/Rnrd7qifTEm9IpKb5nH8ldFf0Mv3Aqkk3RwtLmOudf356oVCnMEeK754HKwKB6ipuklIywO1zyug2eW2vB13gXsEGr7IWFjf/2Bz7T1aze1XQRIbxT/fY=
install:
- ./gradlew clean test build publish publishBintray
