language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - secure: fq9zGxW6tWlPs7G7PqJUjOg6+zd4shOZxMyP6WfB5XsMALv30JW7HhexC6TF3YbxdzEaQpf9f+7vnCynXPUKWu9CHixlTfs3jiob2IBgjb3+JucNUBW7XClZEIUAihOu9NpBZGy9zv0Ng79PnkTRrpzzmBmDUbORuACnEomud18=
  - secure: QZBKqgVv3mHq5eVSg0cR7mnj9wcSJxG+ChAqhf0nvOCR7+n+NR7d0SeIXQ5XC1cSosq8MyKcUFQYz7GrCf4DhnZ+4ZYgpTYat3bFGqzdcOWifP/j1k6k54yFje3tY4srpjp5bMB4jhxJvk2+NDScxw/lkhmaHI0RHr8V4DvMGNk=
install:
- ./gradlew clean test build publish publishBintray
