language: java
jdk:
  - oraclejdk8
env:
  global:
  - TERM=dumb
  - secure: UsfVfh3XEx5oC+XOQCVVfnw8fLAP/HvI2bVo2GawP8eZ80AT4D4ZAk9Yj1/C7LOfvgfSIO9H/j9x3983dZPLKQ/z9CRTrBLFLvyEyiCnUTHmqGoSEjsXalR1TlB7B8T0YMnMj0H2L6iRA105rM3NqTCBgFz/kPMOmWV5Kk0ORFM=
  - secure: Zry6t0RMF/McYXFLyssIsp9sU6wfiFUT9vfyBEW4NKnob0f9zXyvYj2KiEiacSeOSL9EZB7xPfUrCJO3hq7YYmjmbwPcQkVmy8d1w3jZhE7pKvPw6Dda5ejxPr2V7W4FQZJ/cavl5HzctnI9H2vA63jy1NqnSglUM3xIhK590tE=
install: 
  - "./gradlew clean test build publish"
